# Generated by Django 4.1 on 2022-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('phone', models.IntegerField(default=0, verbose_name='Teléfono')),
                ('mail', models.CharField(max_length=128, verbose_name='Correo')),
            ],
            options={
                'db_table': 'becarios',
            },
        ),
    ]
