# Generated by Django 4.1 on 2022-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosbecas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discipline', models.CharField(max_length=128, verbose_name='Disciplina')),
                ('Grade', models.CharField(max_length=128, verbose_name='Grado')),
                ('Country', models.CharField(max_length=128, verbose_name='País')),
                ('University', models.CharField(max_length=128, verbose_name='University')),
            ],
            options={
                'db_table': 'estudios',
            },
        ),
    ]
