# Generated by Django 4.1 on 2022-08-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datosbecas', '0002_estudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_date', models.DateField(verbose_name='Fecha de inicio')),
                ('End_date', models.DateField(verbose_name='Fecha final')),
                ('Status', models.CharField(max_length=128, verbose_name='Estado de la beca')),
                ('Create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('Becario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datosbecas.becario', verbose_name='Becario')),
            ],
            options={
                'db_table': 'becas',
            },
        ),
    ]
